#!/usr/bin/bash

if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  xbacklight -inc 10
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  xbacklight -dec 10
fi

brightness=$(xbacklight -get)
short=${brightness:0:3}

if [[ "${short}" == "100" ]]; then
  echo ${short}%
  echo ""
else
  echo ${short:0:2}%
  echo ""
fi


